version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:v0.17
    environment:
      PGDATABASE: breedbase
      PGHOST: breedbase_db
      PGPASSWORD: postgres
      PGUSER: postgres
    depends_on:
      breedbase_db:
        condition: service_healthy
    container_name: breedbase_web

  breedbase_db:
    image: postgres:12.6
    container_name: breedbase_db
    environment:
      POSTGRES_DB: breedbase
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres -d $${POSTGRES_DB} || exit 1"
      interval: 10s
